/*

 MELKIY.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Melkiy[] =
{
  0x48,0x48,0xFC,0xFC,0xFC,0xFC,0xAD,0xFD,
  0xFD,0xFD,0x7F,0x7F,0x3F,0x3F,0x35,0x3F,
  0x48,0x48,0xFC,0xFC,0xFC,0xFC,0xD5,0xFD,
  0xFD,0xFD,0x7F,0x7F,0x3F,0x3F,0x2B,0x3F
};

/* End of MELKIY.C */
